spring:
  data.mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false