spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    producer:
      bootstrap-servers: localhost:10001,localhost:10002,localhost:10003
    consumer:
      group-id: ball-consumer
      bootstrap-servers: localhost:10001,localhost:10002,localhost:10003
      auto-offset-reset: earliest
app:
  auth:
    issuer: ${ACCESS_TOKEN_ISSUER:project-coco}
    access-token-secret: ${ACCESS_TOKEN_SECRET:access-token-secret}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET:refresh-token-secret}
    access-token-expiration: 2h
    refresh-token-expiration: 14d